from __future__ import annotations

import json
import re
import shutil
from pathlib import Path
from typing import Any

from .layout import Layout
from .scenario import HotspotSettings, PowerModel, ThermalPackage


def write_flp(layout: Layout, path: str | Path) -> Path:
    path = Path(path)
    scale = layout.length_scale_to_m
    with path.open("w", encoding="utf-8") as fp:
        fp.write("# Generated by ChipTherm\n")
        fp.write("# name\twidth\theight\tleft-x\tbottom-y\n")
        for chiplet in layout.chiplets:
            fp.write(
                f"{chiplet.name}\t"
                f"{chiplet.size.width * scale:.12g}\t"
                f"{chiplet.size.height * scale:.12g}\t"
                f"{chiplet.left_x * scale:.12g}\t"
                f"{chiplet.bottom_y * scale:.12g}\n"
            )
    return path


def write_ptrace(layout: Layout, power: PowerModel, path: str | Path) -> Path:
    path = Path(path)
    with path.open("w", encoding="utf-8") as fp:
        fp.write("\t".join(chiplet.name for chiplet in layout.chiplets))
        fp.write("\n")
        fp.write("\t".join(f"{power.chiplet_watts[chiplet.name]:.12g}" for chiplet in layout.chiplets))
        fp.write("\n")
    return path


def write_hotspot_config(
    template_path: str | Path,
    output_path: str | Path,
    package: ThermalPackage,
    hotspot: HotspotSettings,
) -> Path:
    options = dict(package.options)
    options.update(
        {
            "-model_type": hotspot.model_type,
            "-grid_rows": hotspot.grid_rows,
            "-grid_cols": hotspot.grid_cols,
            "-grid_map_mode": hotspot.grid_map_mode,
            "-sampling_intvl": hotspot.sampling_interval_s,
            "-base_proc_freq": hotspot.base_processor_frequency_Hz,
            "-leakage_used": int(hotspot.leakage_used),
            "-package_model_used": int(hotspot.detailed_package),
            "-model_secondary": int(hotspot.secondary_path),
        }
    )
    text = Path(template_path).read_text(encoding="utf-8")
    rendered = _replace_config_options(text, options)
    output_path = Path(output_path)
    output_path.write_text(rendered, encoding="utf-8")
    return output_path


def write_manifest(path: str | Path, data: dict[str, Any]) -> Path:
    path = Path(path)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def copy_source_files(paths: list[Path], source_dir: str | Path) -> None:
    source_dir = Path(source_dir)
    source_dir.mkdir(parents=True, exist_ok=True)
    for path in paths:
        shutil.copyfile(path, source_dir / path.name)


def read_grid_shape(config_path: str | Path) -> tuple[int, int]:
    values: dict[str, int] = {}
    for line in Path(config_path).read_text(encoding="utf-8").splitlines():
        clean = line.split("#", 1)[0].strip()
        match = re.match(r"^-(grid_rows|grid_cols)\s+(\d+)\b", clean)
        if match:
            values[match.group(1)] = int(match.group(2))

    missing = {"grid_rows", "grid_cols"} - values.keys()
    if missing:
        names = ", ".join(sorted(missing))
        raise ValueError(f"missing HotSpot grid setting(s): {names}")
    return values["grid_rows"], values["grid_cols"]


def _replace_config_options(text: str, options: dict[str, object]) -> str:
    remaining = dict(options)
    lines: list[str] = []
    for line in text.splitlines():
        stripped = line.lstrip()
        match = re.match(r"^(-[A-Za-z0-9_]+)\b", stripped)
        if match and match.group(1) in remaining:
            key = match.group(1)
            indent = line[: len(line) - len(stripped)]
            lines.append(f"{indent}{key}\t\t\t{_format_config_value(remaining.pop(key))}")
        else:
            lines.append(line)

    if remaining:
        lines.append("")
        lines.append("# ChipTherm generated overrides")
        for key in sorted(remaining):
            lines.append(f"{key}\t\t\t{_format_config_value(remaining[key])}")
    return "\n".join(lines) + "\n"


def _format_config_value(value: object) -> str:
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, float):
        return f"{value:.12g}"
    return str(value)
